'use client'

import React, { useState, useEffect } from 'react'
import {
    SparklesIcon,
    PencilIcon,
    ArrowPathIcon,
    XMarkIcon,
} from '@heroicons/react/24/outline'
import { CustomRowFormData, CUSTOM_ROW_CONSTRAINTS } from '../../types/customRows'
import { MOVIE_GENRES, TV_GENRES } from '../../constants/genres'
import { Content, getTitle } from '../../typings'
import Image from 'next/image'

interface WizardStep3NamePreviewProps {
    formData: CustomRowFormData
    onChange: (updates: Partial<CustomRowFormData>) => void
    onBack: () => void
    onCreate: () => void
    isCreating: boolean
    isAuthenticated: boolean
    onSignIn: () => void
}

/**
 * WizardStep3NamePreview Component
 *
 * Third step of custom row creation wizard.
 * Auto-generates collection name and previews content.
 */
export function WizardStep3NamePreview({
    formData,
    onChange,
    onBack,
    onCreate,
    isCreating,
    isAuthenticated,
    onSignIn,
}: WizardStep3NamePreviewProps) {
    const [isGeneratingName, setIsGeneratingName] = useState(false)
    const [isLoadingPreview, setIsLoadingPreview] = useState(false)
    const [nameError, setNameError] = useState<string | null>(null)
    const [isEditingName, setIsEditingName] = useState(false)
    const [previewContent, setPreviewContent] = useState<Content[]>([])
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
    const [currentPreviewPage, setCurrentPreviewPage] = useState(0)
    const [isLoadingMoreSuggestions, setIsLoadingMoreSuggestions] = useState(false)
    const [currentTMDBPage, setCurrentTMDBPage] = useState(1)

    // Get genre names for display
    const genreList = formData.mediaType === 'tv' ? TV_GENRES : MOVIE_GENRES
    const selectedGenreNames = formData.genres
        .map((id) => genreList.find((g) => g.id === id)?.name)
        .filter(Boolean)

    // Check if name is valid
    const isNameValid =
        formData.name.trim().length >= CUSTOM_ROW_CONSTRAINTS.MIN_NAME_LENGTH &&
        formData.name.trim().length <= CUSTOM_ROW_CONSTRAINTS.MAX_NAME_LENGTH

    // Auto-generate name and fetch preview when component mounts
    useEffect(() => {
        if (!hasAutoGenerated) {
            // Generate name automatically
            handleGenerateName()
            // Fetch content preview automatically
            fetchContentPreview()
            setHasAutoGenerated(true)
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    // Sync preview content to form data whenever it changes
    useEffect(() => {
        console.log('WizardStep3 - previewContent changed:', previewContent.length, 'items')
        if (previewContent.length > 0) {
            console.log('WizardStep3 - calling onChange with previewContent')
            onChange({ previewContent })
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [previewContent])

    // Handle AI name generation
    const handleGenerateName = async () => {
        if (!isAuthenticated) {
            // Generate a basic name without AI if not authenticated
            const genreNames = selectedGenreNames.join(' & ')
            onChange({ name: `${genreNames} ${formData.mediaType === 'tv' ? 'Shows' : 'Movies'}` })
            return
        }

        setIsGeneratingName(true)
        setNameError(null)

        try {
            const response = await fetch('/api/generate-row-name', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    genres: formData.genres,
                    genreLogic: formData.genreLogic,
                    mediaType: formData.mediaType,
                    advancedFilters: formData.advancedFilters,
                    previewContent: previewContent.slice(0, 10), // Send first 10 titles for context
                }),
            })

            if (!response.ok) {
                throw new Error('Failed to generate name')
            }

            const data = await response.json()
            onChange({ name: data.name })
        } catch (error) {
            console.error('Error generating name:', error)
            setNameError('Failed to generate name. Please try again or enter one manually.')
            // Fallback to basic name
            const genreNames = selectedGenreNames.join(' & ')
            onChange({ name: `${genreNames} ${formData.mediaType === 'tv' ? 'Shows' : 'Movies'}` })
        } finally {
            setIsGeneratingName(false)
        }
    }

    // Fetch content preview based on filters
    const fetchContentPreview = async (page: number = 1, append: boolean = false) => {
        setIsLoadingPreview(true)
        try {
            // Build query params for TMDB API using the new discover endpoint
            const params = new URLSearchParams()

            // Media type
            params.append('media_type', formData.mediaType === 'both' ? 'movie' : formData.mediaType)

            // Genres
            if (formData.genres.length > 0) {
                params.append('with_genres', formData.genres.join(','))
            }

            // Page
            params.append('page', page.toString())

            // Add advanced filters if they exist
            if (formData.advancedFilters) {
                const filters = formData.advancedFilters

                // Rating filters
                if (filters.ratingMin !== undefined) {
                    params.append('vote_average.gte', filters.ratingMin.toString())
                }
                if (filters.ratingMax !== undefined) {
                    params.append('vote_average.lte', filters.ratingMax.toString())
                }

                // Year filters (use appropriate param based on media type)
                if (formData.mediaType === 'tv') {
                    if (filters.yearMin) {
                        params.append('first_air_date.gte', `${filters.yearMin}-01-01`)
                    }
                    if (filters.yearMax) {
                        params.append('first_air_date.lte', `${filters.yearMax}-12-31`)
                    }
                } else {
                    if (filters.yearMin) {
                        params.append('primary_release_date.gte', `${filters.yearMin}-01-01`)
                    }
                    if (filters.yearMax) {
                        params.append('primary_release_date.lte', `${filters.yearMax}-12-31`)
                    }
                }

                // Vote count filter
                if (filters.voteCount !== undefined) {
                    // Map vote count index (0-4) to values
                    const voteCountValues = [0, 100, 1000, 5000, 10000]
                    params.append('vote_count.gte', voteCountValues[filters.voteCount].toString())
                }
            }

            const response = await fetch(`/api/discover?${params.toString()}`)
            if (!response.ok) {
                const errorData = await response.json()
                throw new Error(errorData.message || 'Failed to fetch content preview')
            }

            const data = await response.json()
            if (append) {
                setPreviewContent((prev) => [...prev, ...data.results])
            } else {
                setPreviewContent(data.results)
            }
        } catch (error) {
            console.error('Error fetching preview:', error)
            if (!append) {
                setPreviewContent([])
            }
        } finally {
            setIsLoadingPreview(false)
        }
    }

    // Load more suggestions from next TMDB page
    const loadMoreSuggestions = async () => {
        setIsLoadingMoreSuggestions(true)
        const nextPage = currentTMDBPage + 1
        await fetchContentPreview(nextPage, true)
        setCurrentTMDBPage(nextPage)
        setIsLoadingMoreSuggestions(false)
    }

    // Count active advanced filters
    const activeFilterCount = formData.advancedFilters
        ? Object.keys(formData.advancedFilters).filter((key) => {
              const value = formData.advancedFilters![key as keyof typeof formData.advancedFilters]
              return value !== undefined && value !== null && value !== ''
          }).length
        : 0

    return (
        <div className="space-y-6">
            {/* Filter Summary Card */}
            <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-4">
                <h4 className="text-white font-medium mb-3">Your Selection</h4>

                <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                        <span className="text-gray-400">Media Type:</span>
                        <span className="text-white capitalize">{formData.mediaType}</span>
                    </div>

                    <div className="flex justify-between">
                        <span className="text-gray-400">Genres:</span>
                        <span className="text-white text-right max-w-xs">
                            {selectedGenreNames.join(', ')}
                        </span>
                    </div>

                    {formData.genres.length > 1 && (
                        <div className="flex justify-between">
                            <span className="text-gray-400">Logic:</span>
                            <span className="text-white">Match {formData.genreLogic}</span>
                        </div>
                    )}

                    {activeFilterCount > 0 && (
                        <>
                            <div className="border-t border-gray-700 my-2 pt-2">
                                <span className="text-red-400 font-medium text-xs">
                                    {activeFilterCount} Advanced Filter
                                    {activeFilterCount > 1 ? 's' : ''} Applied
                                </span>
                            </div>
                        </>
                    )}
                </div>
            </div>

            {/* Name with Edit and Refresh */}
            <div>
                <label htmlFor="collectionName" className="block text-sm font-medium text-gray-200 mb-2">
                    Name *
                </label>

                <div className="flex items-center gap-2">
                    {isEditingName ? (
                        <>
                            <input
                                type="text"
                                id="collectionName"
                                value={formData.name}
                                onChange={(e) => {
                                    onChange({ name: e.target.value })
                                    setNameError(null)
                                }}
                                placeholder="e.g., Epic Sci-Fi Adventures"
                                maxLength={CUSTOM_ROW_CONSTRAINTS.MAX_NAME_LENGTH}
                                className="flex-1 px-4 py-3 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:border-red-500 focus:outline-none focus:ring-1 focus:ring-red-500"
                                autoFocus
                            />
                            <button
                                type="button"
                                onClick={() => setIsEditingName(false)}
                                className="p-3 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition-colors"
                                title="Done editing"
                            >
                                <XMarkIcon className="w-5 h-5" />
                            </button>
                        </>
                    ) : (
                        <>
                            <div className="flex-1 px-4 py-3 bg-gray-800 border border-gray-700 rounded-lg text-white">
                                {isGeneratingName ? (
                                    <span className="flex items-center gap-2 text-gray-400">
                                        <SparklesIcon className="w-4 h-4 animate-pulse" />
                                        Generating name...
                                    </span>
                                ) : (
                                    formData.name || 'No name yet'
                                )}
                            </div>
                            <button
                                type="button"
                                onClick={() => setIsEditingName(true)}
                                className="p-3 bg-blue-600/20 border border-blue-500/30 text-blue-400 rounded-lg hover:bg-blue-600/30 transition-colors"
                                title="Edit name"
                            >
                                <PencilIcon className="w-5 h-5" />
                            </button>
                            <button
                                type="button"
                                onClick={handleGenerateName}
                                disabled={isGeneratingName}
                                className="p-3 bg-purple-600/20 border border-purple-500/30 text-purple-400 rounded-lg hover:bg-purple-600/30 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                title="Generate new name"
                            >
                                <ArrowPathIcon className={`w-5 h-5 ${isGeneratingName ? 'animate-spin' : ''}`} />
                            </button>
                        </>
                    )}
                </div>

                <div className="flex justify-between items-center mt-2">
                    <div>
                        {nameError && <p className="text-sm text-red-500">{nameError}</p>}
                        {!isNameValid && formData.name.length > 0 && (
                            <p className="text-sm text-yellow-500">
                                {formData.name.length < CUSTOM_ROW_CONSTRAINTS.MIN_NAME_LENGTH
                                    ? `At least ${CUSTOM_ROW_CONSTRAINTS.MIN_NAME_LENGTH} characters required`
                                    : 'Name too long'}
                            </p>
                        )}
                    </div>
                    <p className="text-sm text-gray-400">
                        {formData.name.length}/{CUSTOM_ROW_CONSTRAINTS.MAX_NAME_LENGTH}
                    </p>
                </div>
            </div>

            {/* Content Preview */}
            <div>
                <div className="flex items-center justify-between mb-3">
                    <h4 className="text-white font-medium">
                        Content Preview
                        {isLoadingPreview && (
                            <span className="text-gray-400 text-sm ml-2">(Loading...)</span>
                        )}
                    </h4>
                    {previewContent.length > 0 && (
                        <button
                            onClick={loadMoreSuggestions}
                            disabled={isLoadingMoreSuggestions}
                            className="flex items-center gap-2 px-3 py-1.5 bg-purple-600/20 border border-purple-500/30 text-purple-400 rounded-lg hover:bg-purple-600/30 transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm"
                        >
                            <SparklesIcon className={`w-4 h-4 ${isLoadingMoreSuggestions ? 'animate-pulse' : ''}`} />
                            {isLoadingMoreSuggestions ? 'Loading...' : 'Infinite Suggestions'}
                        </button>
                    )}
                </div>

                {isLoadingPreview && previewContent.length === 0 ? (
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
                        {Array.from({ length: 10 }).map((_, i) => (
                            <div key={i} className="aspect-[2/3] bg-gray-800 rounded-md animate-pulse" />
                        ))}
                    </div>
                ) : previewContent.length > 0 ? (
                    <>
                        {/* 2 rows max - 10 items per page (5 cols × 2 rows) */}
                        <div className="relative overflow-hidden">
                            <div
                                className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 transition-all duration-500 ease-in-out"
                                style={{
                                    transform: `translateX(-${currentPreviewPage * 100}%)`,
                                }}
                            >
                                {previewContent.map((content, index) => (
                                    <div
                                        key={`${content.id}-${index}`}
                                        className="relative aspect-[2/3] bg-gray-800 rounded-md overflow-hidden group cursor-pointer hover:ring-2 hover:ring-red-500 transition-all"
                                        style={{
                                            gridColumn:
                                                Math.floor(index / 10) === currentPreviewPage
                                                    ? 'auto'
                                                    : 'span 1',
                                            display:
                                                Math.floor(index / 10) === currentPreviewPage
                                                    ? 'block'
                                                    : 'none',
                                        }}
                                    >
                                        {content.poster_path && (
                                            <Image
                                                src={`https://image.tmdb.org/t/p/w342${content.poster_path}`}
                                                alt={getTitle(content)}
                                                fill
                                                className="object-cover"
                                                sizes="(max-width: 640px) 50vw, (max-width: 768px) 33vw, (max-width: 1024px) 25vw, 20vw"
                                            />
                                        )}
                                        {/* Rating Badge */}
                                        {content.vote_average > 0 && (
                                            <div className="absolute top-2 left-2 bg-black/80 backdrop-blur-sm rounded-full px-2 py-1 z-10">
                                                <div className="flex items-center gap-1">
                                                    <span className="text-yellow-400 text-xs">⭐</span>
                                                    <span className="text-white text-xs font-medium">
                                                        {content.vote_average.toFixed(1)}
                                                    </span>
                                                </div>
                                            </div>
                                        )}
                                        {/* Title overlay on hover */}
                                        <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/0 to-black/0 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <div className="absolute bottom-0 left-0 right-0 p-2">
                                                <p className="text-white text-xs font-medium line-clamp-2">
                                                    {getTitle(content)}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Pagination Controls */}
                        {previewContent.length > 10 && (
                            <div className="flex items-center justify-center gap-2 mt-4">
                                <button
                                    onClick={() => setCurrentPreviewPage((prev) => Math.max(0, prev - 1))}
                                    disabled={currentPreviewPage === 0}
                                    className="px-3 py-1.5 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm"
                                >
                                    ← Previous
                                </button>
                                <span className="text-sm text-gray-400">
                                    Page {currentPreviewPage + 1} of {Math.ceil(previewContent.length / 10)}
                                </span>
                                <button
                                    onClick={() =>
                                        setCurrentPreviewPage((prev) =>
                                            Math.min(Math.ceil(previewContent.length / 10) - 1, prev + 1)
                                        )
                                    }
                                    disabled={
                                        currentPreviewPage >= Math.ceil(previewContent.length / 10) - 1
                                    }
                                    className="px-3 py-1.5 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm"
                                >
                                    Next →
                                </button>
                            </div>
                        )}
                    </>
                ) : (
                    <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-8 text-center">
                        <p className="text-gray-400">No content found matching your filters</p>
                    </div>
                )}
            </div>

            {/* Navigation Buttons */}
            <div className="flex gap-3 pt-4">
                <button
                    type="button"
                    onClick={onBack}
                    className="px-6 py-3 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition-colors font-medium"
                >
                    ← Back
                </button>
                <button
                    type="button"
                    onClick={onCreate}
                    disabled={!isNameValid || isCreating}
                    className="flex-1 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium"
                >
                    {isCreating ? 'Creating Collection...' : 'Create Collection'}
                </button>
            </div>
        </div>
    )
}
