/**
 * Rankings Drizzle query module.
 *
 * Replaces utils/firestore/rankings.ts. All Firestore primitives are mapped:
 *   - increment()         → sql`${col} + 1` / sql`${col} - 1`
 *   - runTransaction()    → db.transaction()
 *   - writeBatch()        → db.transaction() (batch updates in a single tx)
 *   - arrays / objects    → JSON columns (Drizzle handles serialisation)
 *
 * Ownership is always derived from the Auth.js session by the API route layer
 * (via withAuth); the functions here trust the userId passed by the route.
 */

import { and, desc, eq, inArray, sql } from 'drizzle-orm'

import { db } from '@/db'
import { rankingLikes, rankings } from '@/db/schema'
import type {
    CreateRankingRequest,
    RankedItem,
    Ranking,
    UpdateRankingRequest,
} from '@/types/rankings'

/* -------------------------------------------------------------------------- */
/*  Internal helpers                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Extract denormalised content metadata from ranked items.
 * Mirrors extractContentMetadata() in the old Firestore module.
 */
function extractContentMetadata(rankedItems: RankedItem[]): {
    contentIds: number[]
    contentTitles: string[]
} {
    const contentIds: number[] = []
    const contentTitles: string[] = []

    for (const item of rankedItems) {
        contentIds.push(item.content.id)
        const title = 'title' in item.content ? item.content.title : item.content.name
        if (title) {
            contentTitles.push(title.toLowerCase())
        }
    }

    return { contentIds, contentTitles }
}

/** Map a raw DB row to the Ranking domain type. */
function rowToRanking(row: typeof rankings.$inferSelect): Ranking {
    return {
        id: row.id,
        userId: row.userId,
        userName: row.userName ?? '',
        userAvatar: row.userAvatar ?? null,
        userUsername: row.userUsername ?? undefined,
        title: row.title,
        description: row.description ?? undefined,
        rankedItems: (row.rankedItems as RankedItem[]) ?? [],
        isPublic: row.isPublic,
        itemCount: row.itemCount,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
        likes: row.likes,
        comments: row.comments,
        views: row.views,
        contentIds: (row.contentIds as number[]) ?? [],
        contentTitles: (row.contentTitles as string[]) ?? [],
        shareSettings: row.shareSettings ?? undefined,
        sharedLinkId: row.sharedLinkId ?? undefined,
    }
}

/* -------------------------------------------------------------------------- */
/*  CRUD                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Create a new ranking and return the persisted Ranking.
 *
 * Mirrors createRanking() in the old Firestore module.
 * The id is generated by the schema default (crypto.randomUUID).
 */
export async function createRanking(
    userId: string,
    displayName: string,
    username: string | undefined,
    userAvatar: string | undefined,
    request: CreateRankingRequest
): Promise<Ranking> {
    const ts = Date.now()

    const inserted = await db
        .insert(rankings)
        .values({
            userId,
            userName: displayName,
            userUsername: username ?? null,
            userAvatar: userAvatar ?? null,
            title: request.title.trim(),
            description: request.description?.trim() ?? null,
            rankedItems: [] as RankedItem[],
            isPublic: request.isPublic ?? true,
            itemCount: request.itemCount,
            createdAt: ts,
            updatedAt: ts,
            likes: 0,
            comments: 0,
            views: 0,
            contentIds: [] as number[],
            contentTitles: [] as string[],
        })
        .returning()

    return rowToRanking(inserted[0])
}

/** Fetch a single ranking by ID. Returns null when not found. */
export async function getRanking(rankingId: string): Promise<Ranking | null> {
    const rows = await db.select().from(rankings).where(eq(rankings.id, rankingId)).limit(1)

    return rows.length > 0 ? rowToRanking(rows[0]) : null
}

/** Fetch all rankings belonging to a user, newest-updated first. */
export async function getUserRankings(userId: string): Promise<Ranking[]> {
    const rows = await db
        .select()
        .from(rankings)
        .where(eq(rankings.userId, userId))
        .orderBy(desc(rankings.updatedAt))
        .limit(50)

    return rows.map(rowToRanking)
}

/**
 * Fetch public rankings with the requested sort order.
 *
 * Pagination is offset-based (cursor-after not needed for SQLite at this scale).
 */
export async function getPublicRankings(
    sortBy: 'recent' | 'popular' | 'most-liked' | 'most-viewed',
    limitCount: number = 50,
    offset: number = 0
): Promise<{ data: Ranking[]; hasMore: boolean }> {
    let orderCol: Parameters<typeof desc>[0]
    switch (sortBy) {
        case 'most-liked':
            orderCol = rankings.likes
            break
        case 'most-viewed':
            orderCol = rankings.views
            break
        case 'popular':
            // Approximation: sort by likes as in the old Firestore module
            orderCol = rankings.likes
            break
        case 'recent':
        default:
            orderCol = rankings.createdAt
            break
    }

    const rows = await db
        .select()
        .from(rankings)
        .where(eq(rankings.isPublic, true))
        .orderBy(desc(orderCol))
        .limit(limitCount + 1) // fetch one extra to detect hasMore
        .offset(offset)

    const hasMore = rows.length > limitCount
    return {
        data: rows.slice(0, limitCount).map(rowToRanking),
        hasMore,
    }
}

/**
 * Update an existing ranking.
 *
 * Ownership check must be performed by the caller (API route) using the session
 * userId. This function performs a DB-level transaction to atomically update the
 * row and re-extract denormalised metadata when rankedItems change.
 */
export async function updateRanking(
    userId: string,
    rankingId: string,
    updates: UpdateRankingRequest
): Promise<void> {
    await db.transaction(async (tx) => {
        // Ownership check inside the transaction
        const existing = await tx
            .select({ userId: rankings.userId })
            .from(rankings)
            .where(eq(rankings.id, rankingId))
            .limit(1)

        if (existing.length === 0) {
            throw new Error(`Ranking not found: ${rankingId}`)
        }
        if (existing[0].userId !== userId) {
            throw new Error('Unauthorized: you do not own this ranking')
        }

        // Build the update patch
        const patch: Partial<typeof rankings.$inferInsert> & { updatedAt: number } = {
            updatedAt: Date.now(),
        }

        if (updates.title !== undefined) patch.title = updates.title.trim()
        if (updates.description !== undefined) patch.description = updates.description.trim()
        if (updates.isPublic !== undefined) patch.isPublic = updates.isPublic
        if (updates.itemCount !== undefined) patch.itemCount = updates.itemCount

        if (updates.rankedItems !== undefined) {
            patch.rankedItems = updates.rankedItems
            const { contentIds, contentTitles } = extractContentMetadata(updates.rankedItems)
            patch.contentIds = contentIds
            patch.contentTitles = contentTitles
        }

        await tx.update(rankings).set(patch).where(eq(rankings.id, rankingId))
    })
}

/**
 * Delete a ranking and all its associated data (likes, comments, comment likes).
 *
 * SQLite foreign-key cascades handle the child rows automatically when the
 * schema `onDelete: 'cascade'` is set, but our ranking_likes / ranking_comments /
 * comment_likes tables reference `users.id` — not `rankings.id` — so we must
 * delete child rows manually in a transaction.
 *
 * Ownership is verified by the caller (API route) before calling this.
 */
export async function deleteRankingWithCascade(rankingId: string): Promise<{
    rankingLikesDeleted: number
    commentsDeleted: number
    commentLikesDeleted: number
}> {
    // Import comment table references here to keep the circular dependency
    // between rankings/rankingComments modules explicit.
    const { rankingComments, commentLikes } = await import('@/db/schema')

    return await db.transaction(async (tx) => {
        // 1. Delete ranking likes
        const deletedRankingLikes = await tx
            .delete(rankingLikes)
            .where(eq(rankingLikes.rankingId, rankingId))
            .returning({ id: rankingLikes.id })

        // 2. Collect comment IDs so we can delete comment likes
        const commentRows = await tx
            .select({ id: rankingComments.id })
            .from(rankingComments)
            .where(eq(rankingComments.rankingId, rankingId))

        const commentIds = commentRows.map((r) => r.id)

        let deletedCommentLikeCount = 0
        if (commentIds.length > 0) {
            const deletedCommentLikes = await tx
                .delete(commentLikes)
                .where(inArray(commentLikes.commentId, commentIds))
                .returning({ id: commentLikes.id })
            deletedCommentLikeCount = deletedCommentLikes.length
        }

        // 3. Delete comments
        const deletedComments = await tx
            .delete(rankingComments)
            .where(eq(rankingComments.rankingId, rankingId))
            .returning({ id: rankingComments.id })

        // 4. Delete the ranking itself
        await tx.delete(rankings).where(eq(rankings.id, rankingId))

        return {
            rankingLikesDeleted: deletedRankingLikes.length,
            commentsDeleted: deletedComments.length,
            commentLikesDeleted: deletedCommentLikeCount,
        }
    })
}

/* -------------------------------------------------------------------------- */
/*  Likes                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Like a ranking.
 *
 * Uses a transaction that checks for an existing like record, inserts one if
 * absent, and increments the denormalised likes counter atomically.
 * Returns true when the like was newly created, false if already liked.
 */
export async function likeRanking(userId: string, rankingId: string): Promise<boolean> {
    return await db.transaction(async (tx) => {
        // Check for existing like
        const existing = await tx
            .select({ id: rankingLikes.id })
            .from(rankingLikes)
            .where(and(eq(rankingLikes.userId, userId), eq(rankingLikes.rankingId, rankingId)))
            .limit(1)

        if (existing.length > 0) {
            return false // Already liked
        }

        // Insert like record
        await tx.insert(rankingLikes).values({
            rankingId,
            userId,
            createdAt: Date.now(),
        })

        // Increment counter — sql`` prevents N+1 read-modify-write race
        await tx
            .update(rankings)
            .set({ likes: sql`${rankings.likes} + 1` })
            .where(eq(rankings.id, rankingId))

        return true
    })
}

/**
 * Unlike a ranking.
 *
 * Deletes the like record and decrements the counter (floor 0).
 * Returns true when the unlike was applied, false if no like existed.
 */
export async function unlikeRanking(userId: string, rankingId: string): Promise<boolean> {
    return await db.transaction(async (tx) => {
        const existing = await tx
            .select({ id: rankingLikes.id })
            .from(rankingLikes)
            .where(and(eq(rankingLikes.userId, userId), eq(rankingLikes.rankingId, rankingId)))
            .limit(1)

        if (existing.length === 0) {
            return false // Not liked
        }

        await tx
            .delete(rankingLikes)
            .where(and(eq(rankingLikes.userId, userId), eq(rankingLikes.rankingId, rankingId)))

        await tx
            .update(rankings)
            .set({ likes: sql`MAX(0, ${rankings.likes} - 1)` })
            .where(eq(rankings.id, rankingId))

        return true
    })
}

/** Check whether a user has liked a ranking. */
export async function hasUserLikedRanking(userId: string, rankingId: string): Promise<boolean> {
    const rows = await db
        .select({ id: rankingLikes.id })
        .from(rankingLikes)
        .where(and(eq(rankingLikes.userId, userId), eq(rankingLikes.rankingId, rankingId)))
        .limit(1)

    return rows.length > 0
}

/* -------------------------------------------------------------------------- */
/*  View tracking                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Increment the view counter for a ranking.
 *
 * Mirrors incrementRankingView() in the old Firestore module.
 * If a viewerId is supplied the function skips incrementing when the viewer is
 * the ranking owner (same behaviour as before).
 */
export async function incrementRankingView(
    rankingId: string,
    viewerId?: string | null
): Promise<void> {
    // When viewerId is supplied, skip if the viewer is the owner
    if (viewerId) {
        const row = await db
            .select({ userId: rankings.userId })
            .from(rankings)
            .where(eq(rankings.id, rankingId))
            .limit(1)

        if (row.length > 0 && row[0].userId === viewerId) {
            return // Owner viewing their own ranking — don't count
        }
    }

    await db
        .update(rankings)
        .set({ views: sql`${rankings.views} + 1` })
        .where(eq(rankings.id, rankingId))
}

/* -------------------------------------------------------------------------- */
/*  Username denormalisation                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Update the denormalised userName / userUsername across all rankings owned by
 * a user. Mirrors updateRankingsUsername() in the old Firestore module.
 * SQLite has no batch-write limit so a single transaction suffices.
 */
export async function updateRankingsUsername(
    userId: string,
    newDisplayName: string,
    newUsername?: string
): Promise<void> {
    const patch: Partial<typeof rankings.$inferInsert> = {
        userName: newDisplayName,
        updatedAt: Date.now(),
    }
    if (newUsername !== undefined) {
        patch.userUsername = newUsername
    }

    await db.update(rankings).set(patch).where(eq(rankings.userId, userId))
}
